In [101]:
import numpy as np

In [102]:
my_list = [1,2,3,4]

In [103]:
arr = np.array(my_list)

In [104]:
print(arr)

[1 2 3 4]


In [105]:
np.random.rand(6)

array([0.95287671, 0.34363158, 0.86509982, 0.83027771, 0.53816145,
       0.92246937])

In [106]:
np.random.randint(1,50,10)

array([34, 30, 25, 37, 20, 36, 31, 11, 40, 21])

In [107]:
arr = np.arange(0,11)

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [110]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
narr = arr > 5

In [112]:
arr[narr]

array([ 6,  7,  8,  9, 10])

In [113]:
import pandas as pd

In [114]:
my_data = [10,20,30]
labels = ['a','b','c']

In [115]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [116]:
np.random.seed(101)

In [117]:
df = pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['w','x','y','z'])

In [118]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [119]:
bf = pd.DataFrame(np.random.randn(2,2),['a','b'],['w','x'])

In [120]:
bf

w         x
a  0.302665  1.693723
b -1.706086 -1.159119

In [121]:
bf[['w','x']]

w         x
a  0.302665  1.693723
b -1.706086 -1.159119

In [122]:
bf['z'] = bf['w'] + bf['x']

In [123]:
bf

w         x         z
a  0.302665  1.693723  1.996388
b -1.706086 -1.159119 -2.865205

In [125]:
bf.drop('z',axis=1,inplace=True)

In [126]:
bf

w         x
a  0.302665  1.693723
b -1.706086 -1.159119

In [130]:
bf.drop('b',axis=0)

w         x
a  0.302665  1.693723

In [131]:
df.shape

(5, 4)

In [133]:
df.loc['a']

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [134]:
df.iloc[0]

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [135]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [137]:
df.loc['b','y']

-0.8480769834036315

In [138]:
df.loc[['a','b'],['w','y']]

w         y
a  2.706850  0.907969
b  0.651118 -0.848077

In [142]:
kf = pd.DataFrame(np.random.rand(5,4),['z','w','y','u','p'],['e','f','g','h'])

In [143]:
kf

e         f         g         h
z  0.656595  0.209161  0.659925  0.529623
w  0.748520  0.093757  0.784522  0.687242
y  0.695078  0.496867  0.975361  0.203528
u  0.299020  0.227656  0.048169  0.903971
p  0.080104  0.607216  0.630847  0.377942

In [145]:
bl = kf > 0.123


In [147]:
kf[kf<0.4353]

e         f         g         h
z       NaN  0.209161       NaN       NaN
w       NaN  0.093757       NaN       NaN
y       NaN       NaN       NaN  0.203528
u  0.299020  0.227656  0.048169       NaN
p  0.080104       NaN       NaN  0.377942

In [148]:
kf

e         f         g         h
z  0.656595  0.209161  0.659925  0.529623
w  0.748520  0.093757  0.784522  0.687242
y  0.695078  0.496867  0.975361  0.203528
u  0.299020  0.227656  0.048169  0.903971
p  0.080104  0.607216  0.630847  0.377942

In [149]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [150]:
df['w'] > 0

a     True
b     True
c    False
d     True
e     True
Name: w, dtype: bool

In [158]:
df[(df['w']>0) | (df['x']<0)]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [153]:
df[df['w']>0][['z','x']]

z         x
a  0.503826  0.628133
b  0.605965 -0.319318
d  0.955057 -0.758872
e  0.683509  1.978757

In [159]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [160]:
df.reset_index()

index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [161]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [162]:
newkind = 'ca ny wy or cco'.split()

In [163]:
newkind

['ca', 'ny', 'wy', 'or', 'cco']

In [164]:
df['states'] = newkind

In [165]:
df

w         x         y         z states
a  2.706850  0.628133  0.907969  0.503826     ca
b  0.651118 -0.319318 -0.848077  0.605965     ny
c -2.018168  0.740122  0.528813 -0.589001     wy
d  0.188695 -0.758872 -0.933237  0.955057     or
e  0.190794  1.978757  2.605967  0.683509    cco

In [166]:
df.set_index('states')

w         x         y         z
states                                        
ca      2.706850  0.628133  0.907969  0.503826
ny      0.651118 -0.319318 -0.848077  0.605965
wy     -2.018168  0.740122  0.528813 -0.589001
or      0.188695 -0.758872 -0.933237  0.955057
cco     0.190794  1.978757  2.605967  0.683509

In [167]:
df

w         x         y         z states
a  2.706850  0.628133  0.907969  0.503826     ca
b  0.651118 -0.319318 -0.848077  0.605965     ny
c -2.018168  0.740122  0.528813 -0.589001     wy
d  0.188695 -0.758872 -0.933237  0.955057     or
e  0.190794  1.978757  2.605967  0.683509    cco

In [169]:
#index levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)


In [170]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [171]:
inside

[1, 2, 3, 1, 2, 3]

In [172]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [173]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [174]:
df = pd.DataFrame(np.random.randn(6,2),hier_index,['A','B'])

In [175]:
df

A         B
G1 1  0.961458 -2.141212
   2  0.992573  1.192241
   3 -1.046780  1.292765
G2 1 -1.467514 -0.494095
   2 -0.162535  0.485809
   3  0.392489  0.221491

In [177]:
df.index.names = ['Groups','Num']

In [178]:
df

A         B
Groups Num                    
G1     1    0.961458 -2.141212
       2    0.992573  1.192241
       3   -1.046780  1.292765
G2     1   -1.467514 -0.494095
       2   -0.162535  0.485809
       3    0.392489  0.221491

In [182]:
df.loc['G1'].loc[1]

A    0.961458
B   -2.141212
Name: 1, dtype: float64

In [183]:
df

A         B
Groups Num                    
G1     1    0.961458 -2.141212
       2    0.992573  1.192241
       3   -1.046780  1.292765
G2     1   -1.467514 -0.494095
       2   -0.162535  0.485809
       3    0.392489  0.221491

In [189]:
df.loc['G1'].loc[2]['B']

1.1922406372754866

In [190]:
df.xs

<bound method NDFrame.xs of                    A         B
Groups Num                    
G1     1    0.961458 -2.141212
       2    0.992573  1.192241
       3   -1.046780  1.292765
G2     1   -1.467514 -0.494095
       2   -0.162535  0.485809
       3    0.392489  0.221491>

In [192]:
df.xs(1,level= 'Num')

A         B
Groups                    
G1      0.961458 -2.141212
G2     -1.467514 -0.494095

In [193]:
df

A         B
Groups Num                    
G1     1    0.961458 -2.141212
       2    0.992573  1.192241
       3   -1.046780  1.292765
G2     1   -1.467514 -0.494095
       2   -0.162535  0.485809
       3    0.392489  0.221491

In [195]:
alu = df[df>0]

In [197]:
alu.dropna()

A         B
Groups Num                    
G1     2    0.992573  1.192241
G2     3    0.392489  0.221491

In [198]:
alu

A         B
Groups Num                    
G1     1    0.961458       NaN
       2    0.992573  1.192241
       3         NaN  1.292765
G2     1         NaN       NaN
       2         NaN  0.485809
       3    0.392489  0.221491

In [203]:
alu.dropna(thresh=1)

A         B
Groups Num                    
G1     1    0.961458       NaN
       2    0.992573  1.192241
       3         NaN  1.292765
G2     2         NaN  0.485809
       3    0.392489  0.221491

In [206]:
alu.fillna(value='gobar')

A         B
Groups Num                    
G1     1    0.961458     gobar
       2    0.992573  1.192241
       3       gobar  1.292765
G2     1       gobar     gobar
       2       gobar  0.485809
       3    0.392489  0.221491

In [209]:
alu['A'].fillna(value=alu['A'].mean())

Groups  Num
G1      1      0.961458
        2      0.992573
        3      0.782173
G2      1      0.782173
        2      0.782173
        3      0.392489
Name: A, dtype: float64

In [210]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [211]:
df = pd.DataFrame(data)

In [212]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [215]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [216]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
                        

In [219]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                        index=[4, 5, 6, 7]) 

In [220]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [221]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [222]:
df2df

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [223]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [224]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [227]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [228]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [229]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [230]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [232]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [233]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [234]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [235]:
left.join(right,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [236]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [239]:
df['col2'].nunique()

3

In [240]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [241]:
df['col2'].apply(lambda x: x*3)

0    1332
1    1665
2    1998
3    1332
Name: col2, dtype: int64

In [242]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [244]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [245]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [246]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [247]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [248]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN